languageCode = "en-us"
title = "Geofinder API"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	description = "Asset Name"

	logo = "images/asset-hub.svg"
	favicon = "/images/asset-hub.png"

[params.palette]
    primary = "grey"
    accent  = "teal"

[params.font]
    text = "Roboto"
    code = "Roboto Mono"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


[[menu.main]]
	name   = "Problem Solving"
	url    = "/"
	weight = 10
[[menu.main]]
    name   = "Player Scores"
    url    = "playerscores/"
    weight = 200
[[menu.main]]
    name   = "Powertools Example"
    url    = "buildandrun/"
    weight = 900
